import db from '../src/lib/db';

// Hebrew vocabulary for pre-loading
const defaultSections = [
  {
    name: '100 Most Used Words',
    description: 'The 100 most frequently used words in the Hebrew language.',
    isDefault: true,
    words: [
        { hebrew: 'שלום', english: 'Hello / Peace' },
        { hebrew: 'תודה', english: 'Thank you' },
        { hebrew: 'כן', english: 'Yes' },
        { hebrew: 'לא', english: 'No' },
        { hebrew: 'בבקשה', english: 'Please / You\'re welcome' },
        { hebrew: 'סליחה', english: 'Sorry / Excuse me' },
        { hebrew: 'מה', english: 'What' },
        { hebrew: 'מי', english: 'Who' },
        { hebrew: 'מתי', english: 'When' },
        { hebrew: 'איפה', english: 'Where' },
        { hebrew: 'למה', english: 'Why' },
        { hebrew: 'איך', english: 'How' },
        { hebrew: 'אני', english: 'I / Me' },
        { hebrew: 'אתה', english: 'You (m)' },
        { hebrew: 'את', english: 'You (f)' },
        { hebrew: 'הוא', english: 'He' },
        { hebrew: 'היא', english: 'She' },
        { hebrew: 'אנחנו', english: 'We' },
        { hebrew: 'אתם', english: 'You (m, pl)' },
        { hebrew: 'אתן', english: 'You (f, pl)' },
        { hebrew: 'הם', english: 'They (m)' },
        { hebrew: 'הן', english: 'They (f)' },
        { hebrew: 'זה', english: 'This / That (m)' },
        { hebrew: 'זאת', english: 'This / That (f)' },
        { hebrew: 'אלה', english: 'These / Those' },
        { hebrew: 'טוב', english: 'Good' },
        { hebrew: 'רע', english: 'Bad' },
        { hebrew: 'גדול', english: 'Big' },
        { hebrew: 'קטן', english: 'Small' },
        { hebrew: 'הרבה', english: 'A lot / Many' },
        { hebrew: 'קצת', english: 'A little' },
        { hebrew: 'יפה', english: 'Beautiful' },
        { hebrew: 'חדש', english: 'New' },
        { hebrew: 'ישן', english: 'Old' },
        { hebrew: 'מים', english: 'Water' },
        { hebrew: 'אוכל', english: 'Food' },
        { hebrew: 'בית', english: 'House / Home' },
        { hebrew: 'איש', english: 'Man / Person' },
        { hebrew: 'אישה', english: 'Woman / Wife' },
        { hebrew: 'ילד', english: 'Boy / Child' },
        { hebrew: 'ילדה', english: 'Girl' },
        { hebrew: 'יום', english: 'Day' },
        { hebrew: 'לילה', english: 'Night' },
        { hebrew: 'בוקר', english: 'Morning' },
        { hebrew: 'ערב', english: 'Evening' },
        { hebrew: 'עבודה', english: 'Work' },
        { hebrew: 'כסף', english: 'Money' },
        { hebrew: 'אהבה', english: 'Love' },
        { hebrew: 'שם', english: 'Name / There' },
        { hebrew: 'פה', english: 'Here' },
        { hebrew: 'יש', english: 'There is / There are' },
        { hebrew: 'אין', english: 'There isn\'t / There aren\'t' },
        { hebrew: 'הכל', english: 'Everything' },
        { hebrew: 'כלום', english: 'Nothing' },
        { hebrew: 'יותר', english: 'More' },
        { hebrew: 'פחות', english: 'Less' },
        { hebrew: 'תמיד', english: 'Always' },
        { hebrew: 'אף פעם', english: 'Never' },
        { hebrew: 'עכשיו', english: 'Now' },
        { hebrew: 'אחר כך', english: 'Later' },
        { hebrew: 'לפני', english: 'Before' },
        { hebrew: 'אחרי', english: 'After' },
        { hebrew: 'עם', english: 'With' },
        { hebrew: 'בלי', english: 'Without' },
        { hebrew: 'של', english: 'Of / Belonging to' },
        { hebrew: 'את', english: '(Direct object marker)' },
        { hebrew: 'ב', english: 'In / At' },
        { hebrew: 'ל', english: 'To / For' },
        { hebrew: 'מ', english: 'From' },
        { hebrew: 'על', english: 'On / About' },
        { hebrew: 'אל', english: 'To / Towards' },
        { hebrew: 'בין', english: 'Between' },
        { hebrew: 'אבל', english: 'But' },
        { hebrew: 'או', english: 'Or' },
        { hebrew: 'אם', english: 'If' },
        { hebrew: 'כי', english: 'Because' },
        { hebrew: 'אשר', english: 'Which / That' },
        { hebrew: 'גם', english: 'Also / Too' },
        { hebrew: 'רק', english: 'Only' },
        { hebrew: 'מאוד', english: 'Very' },
        { hebrew: 'כמו', english: 'Like / As' },
        { hebrew: 'אחד', english: 'One (m)' },
        { hebrew: 'אחת', english: 'One (f)' },
        { hebrew: 'שניים', english: 'Two (m)' },
        { hebrew: 'שתיים', english: 'Two (f)' },
        { hebrew: 'שלוש', english: 'Three' },
        { hebrew: 'ארבע', english: 'Four' },
        { hebrew: 'חמש', english: 'Five' },
        { hebrew: 'שש', english: 'Six' },
        { hebrew: 'שבע', english: 'Seven' },
        { hebrew: 'שמונה', english: 'Eight' },
        { hebrew: 'תשע', english: 'Nine' },
        { hebrew: 'עשר', english: 'Ten' },
    ],
  },
  {
    name: '100 Most Used Verbs',
    description: 'The 100 most frequently used verbs in the Hebrew language.',
    isDefault: true,
    words: [
        { hebrew: 'להיות', english: 'To be' },
        { hebrew: 'לחיות', english: 'To live' },
        { hebrew: 'לרצות', english: 'To want' },
        { hebrew: 'לעשות', english: 'To do / To make' },
        { hebrew: 'לומר', english: 'To say' },
        { hebrew: 'לדבר', english: 'To speak' },
        { hebrew: 'ללכת', english: 'To go / To walk' },
        { hebrew: 'לבוא', english: 'To come' },
        { hebrew: 'לראות', english: 'To see' },
        { hebrew: 'לשמוע', english: 'To hear' },
        { hebrew: 'לאכול', english: 'To eat' },
        { hebrew: 'לשתות', english: 'To drink' },
        { hebrew: 'לישון', english: 'To sleep' },
        { hebrew: 'לעבוד', english: 'To work' },
        { hebrew: 'ללמוד', english: 'To learn / To study' },
        { hebrew: 'לכתוב', english: 'To write' },
        { hebrew: 'לקרוא', english: 'To read' },
        { hebrew: 'לדעת', english: 'To know' },
        { hebrew: 'להבין', english: 'To understand' },
        { hebrew: 'לחשוב', english: 'To think' },
        { hebrew: 'לאהוב', english: 'To love' },
        { hebrew: 'לתת', english: 'To give' },
        { hebrew: 'לקחת', english: 'To take' },
        { hebrew: 'לפתוח', english: 'To open' },
        { hebrew: 'לסגור', english: 'To close' },
        { hebrew: 'לשאול', english: 'To ask' },
        { hebrew: 'לענות', english: 'To answer' },
        { hebrew: 'לעזור', english: 'To help' },
        { hebrew: 'לשחק', english: 'To play' },
        { hebrew: 'לרוץ', english: 'To run' },
        { hebrew: 'לשבת', english: 'To sit' },
        { hebrew: 'לעמוד', english: 'To stand' },
        { hebrew: 'לשים', english: 'To put' },
        { hebrew: 'למצוא', english: 'To find' },
        { hebrew: 'לצאת', english: 'To go out / To exit' },
        { hebrew: 'להיכנס', english: 'To enter' },
        { hebrew: 'לעלות', english: 'To go up / To cost' },
        { hebrew: 'לרדת', english: 'To go down' },
        { hebrew: 'לחזור', english: 'To return' },
        { hebrew: 'להתחיל', english: 'To start / To begin' },
        { hebrew: 'לגמור', english: 'To finish' },
        { hebrew: 'להשתמש', english: 'To use' },
        { hebrew: 'לנסות', english: 'To try' },
        { hebrew: 'להרגיש', english: 'To feel' },
        { hebrew: 'לזכור', english: 'To remember' },
        { hebrew: 'לשכוח', english: 'To forget' },
        { hebrew: 'לשלם', english: 'To pay' },
        { hebrew: 'לקנות', english: 'To buy' },
        { hebrew: 'למכור', english: 'To sell' },
        { hebrew: 'לפגוש', english: 'To meet' },
    ],
  },
  {
    name: 'Family & Relationships',
    description: 'Words related to family and relationships.',
    isDefault: true,
    words: [
      { hebrew: 'משפחה', english: 'Family' },
      { hebrew: 'אמא', english: 'Mother' },
      { hebrew: 'אבא', english: 'Father' },
      { hebrew: 'הורים', english: 'Parents' },
      { hebrew: 'אח', english: 'Brother' },
      { hebrew: 'אחות', english: 'Sister' },
      { hebrew: 'בן', english: 'Son' },
      { hebrew: 'בת', english: 'Daughter' },
      { hebrew: 'סבא', english: 'Grandfather' },
      { hebrew: 'סבתא', english: 'Grandmother' },
      { hebrew: 'דוד', english: 'Uncle' },
      { hebrew: 'דודה', english: 'Aunt' },
      { hebrew: 'בן דוד', english: 'Cousin (m)' },
      { hebrew: 'בת דודה', english: 'Cousin (f)' },
      { hebrew: 'בעל', english: 'Husband' },
      { hebrew: 'אישה', english: 'Wife' },
      { hebrew: 'חבר', english: 'Friend / Boyfriend (m)' },
      { hebrew: 'חברה', english: 'Friend / Girlfriend (f)' },
      { hebrew: 'תינוק', english: 'Baby (m)' },
      { hebrew: 'תינוקת', english: 'Baby (f)' },
    ],
  },
  {
    name: 'Food & Cooking',
    description: 'Vocabulary for food, drinks, and cooking.',
    isDefault: true,
    words: [
      { hebrew: 'לחם', english: 'Bread' },
      { hebrew: 'גבינה', english: 'Cheese' },
      { hebrew: 'עוף', english: 'Chicken' },
      { hebrew: 'בשר', english: 'Meat' },
      { hebrew: 'דג', english: 'Fish' },
      { hebrew: 'ביצה', english: 'Egg' },
      { hebrew: 'ירקות', english: 'Vegetables' },
      { hebrew: 'פירות', english: 'Fruits' },
      { hebrew: 'מים', english: 'Water' },
      { hebrew: 'קפה', english: 'Coffee' },
      { hebrew: 'תה', english: 'Tea' },
      { hebrew: 'מסעדה', english: 'Restaurant' },
      { hebrew: 'מטבח', english: 'Kitchen' },
      { hebrew: 'רעב', english: 'Hungry' },
      { hebrew: 'צמא', english: 'Thirsty' },
      { hebrew: 'טעים', english: 'Delicious' },
    ],
  },
  {
    name: 'Travel & Transportation',
    description: 'Words for traveling and getting around.',
    isDefault: true,
    words: [
      { hebrew: 'מכונית', english: 'Car' },
      { hebrew: 'אוטובוס', english: 'Bus' },
      { hebrew: 'רכבת', english: 'Train' },
      { hebrew: 'מטוס', english: 'Airplane' },
      { hebrew: 'שדה תעופה', english: 'Airport' },
      { hebrew: 'מלון', english: 'Hotel' },
      { hebrew: 'רחוב', english: 'Street' },
      { hebrew: 'עיר', english: 'City' },
      { hebrew: 'מדינה', english: 'Country' },
      { hebrew: 'טיול', english: 'Trip / Hike' },
      { hebrew: 'מפה', english: 'Map' },
      { hebrew: 'ימינה', english: 'Right' },
      { hebrew: 'שמאלה', english: 'Left' },
      { hebrew: 'ישר', english: 'Straight' },
    ],
  },
  {
    name: 'Business & Work',
    description: 'Vocabulary related to business, work, and the office.',
    isDefault: true,
    words: [
      { hebrew: 'עבודה', english: 'Work / Job' },
      { hebrew: 'משרד', english: 'Office' },
      { hebrew: 'חברה', english: 'Company' },
      { hebrew: 'מנהל', english: 'Manager (m)' },
      { hebrew: 'מנהלת', english: 'Manager (f)' },
      { hebrew: 'עובד', english: 'Employee (m)' },
      { hebrew: 'עובדת', english: 'Employee (f)' },
      { hebrew: 'כסף', english: 'Money' },
      { hebrew: 'פגישה', english: 'Meeting' },
      { hebrew: 'מחשב', english: 'Computer' },
      { hebrew: 'טלפון', english: 'Telephone' },
      { hebrew: 'אימייל', english: 'Email' },
    ],
  },
];

async function main() {
  console.log('Starting database seeding...');

  for (const section of defaultSections) {
    try {
      const existingSection = await db.section.findUnique({
        where: { name: section.name },
      });

      if (existingSection) {
        console.log(`Section '${section.name}' already exists. Skipping.`);
        continue;
      }

      const createdSection = await db.section.create({
        data: {
          name: section.name,
          description: section.description,
          isDefault: section.isDefault,
          words: {
            create: section.words.map((w) => ({
              hebrewText: w.hebrew,
              englishTranslation: w.english,
            })),
          },
        },
        include: {
          words: true,
        },
      });
      console.log(`Created section '${createdSection.name}' with ${createdSection.words.length} words.`);
    } catch (error) {
      console.error(`Error creating section '${section.name}':`, error);
    }
  }

  const totalSections = await db.section.count();
  const totalWords = await db.word.count();
  console.log(`Seeding complete. Total sections: ${totalSections}, Total words: ${totalWords}.`);
}

main()
  .catch(async (e) => {
    console.error('Error during seeding:', e);
    await db.$disconnect();
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
