-- AlterTable
ALTER TABLE "public"."UserProgress" ADD COLUMN     "easinessFactor" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
ADD COLUMN     "interval" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "nextReviewDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "quality" INTEGER,
ADD COLUMN     "repetition" INTEGER NOT NULL DEFAULT 0;
